---
layout: post
title: "Presenter at - ÇUKUROVA ÜNİVERSİTESİ-INTERNATIONAL LANGUAGE-FOR-ALL CONFERENCE - LFAC"
date: 2025-10-16
categories: [events]
---
![Alt text for screen readers]({{ site.baseurl }}/images/2022-03-03-Start-of-My-Writing-Thing.jpg)

Before write a lot of thing I wanna mention that in this paragraph everything will be so chaotic and because of my English it is will be more incomprehensible. But this is a not huge problem .The main problem is being patience and being consistent .
